


 
services:
  frontend:
    image: ghcr.io/waruimoojin/frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:51730"
    networks:
      - inventoryflow_network

  backend:
    image: ghcr.io/waruimoojin/backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    networks:
      - inventoryflow_network

networks:
  inventoryflow_network:
    driver: bridge