version: '3.8'

services:
  backend:
    image: yassinenakkabi/inventory_backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    image: yassinenakkabi/inventory_frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    restart: unless-stopped
